#ifndef MINOS_INPUT_H
#define MINOS_INPUT_H

#include <stdint.h>

enum input_key {
    INPUT_KEY_NONE = 0,
    INPUT_KEY_A, INPUT_KEY_B, INPUT_KEY_C, INPUT_KEY_D, INPUT_KEY_E,
    INPUT_KEY_F, INPUT_KEY_G, INPUT_KEY_H, INPUT_KEY_I, INPUT_KEY_J,
    INPUT_KEY_K, INPUT_KEY_L, INPUT_KEY_M, INPUT_KEY_N, INPUT_KEY_O,
    INPUT_KEY_P, INPUT_KEY_Q, INPUT_KEY_R, INPUT_KEY_S, INPUT_KEY_T,
    INPUT_KEY_U, INPUT_KEY_V, INPUT_KEY_W, INPUT_KEY_X, INPUT_KEY_Y,
    INPUT_KEY_Z,
    INPUT_KEY_0, INPUT_KEY_1, INPUT_KEY_2, INPUT_KEY_3, INPUT_KEY_4,
    INPUT_KEY_5, INPUT_KEY_6, INPUT_KEY_7, INPUT_KEY_8, INPUT_KEY_9,
    INPUT_KEY_MINUS, INPUT_KEY_EQUALS, INPUT_KEY_LEFT_BRACKET,
    INPUT_KEY_RIGHT_BRACKET, INPUT_KEY_BACKSLASH, INPUT_KEY_SEMICOLON,
    INPUT_KEY_APOSTROPHE, INPUT_KEY_GRAVE, INPUT_KEY_COMMA,
    INPUT_KEY_PERIOD, INPUT_KEY_SLASH, INPUT_KEY_KP_STAR,
    INPUT_KEY_KP_MINUS, INPUT_KEY_KP_PLUS,
    INPUT_KEY_SPACE, INPUT_KEY_ENTER, INPUT_KEY_BACKSPACE, INPUT_KEY_TAB,
    INPUT_KEY_ESCAPE, INPUT_KEY_LEFT_SHIFT, INPUT_KEY_RIGHT_SHIFT,
    INPUT_KEY_LEFT_CTRL, INPUT_KEY_RIGHT_CTRL, INPUT_KEY_LEFT_ALT,
    INPUT_KEY_RIGHT_ALT, INPUT_KEY_CAPS_LOCK,
    INPUT_KEY_LEFT, INPUT_KEY_RIGHT, INPUT_KEY_UP, INPUT_KEY_DOWN,
    INPUT_KEY_HOME, INPUT_KEY_END, INPUT_KEY_DELETE
};

#define INPUT_MOD_SHIFT  (1U << 0)
#define INPUT_MOD_CTRL   (1U << 1)
#define INPUT_MOD_ALT    (1U << 2)
#define INPUT_MOD_CAPS   (1U << 3)

struct input_event {
    enum input_key key;
    uint8_t pressed;
    uint8_t modifiers;
    char character;
};

void input_init(void);
int input_push(const struct input_event *event);
int input_pop(struct input_event *event);

#endif
