#ifndef MINOS_VMM_H
#define MINOS_VMM_H
#include "../boot/bootinfo.h"
#define MINOS_HIGHER_HALF 0xFFFF800000000000ULL
#define MINOS_HHDM_BASE MINOS_HIGHER_HALF
#define MINOS_HHDM_PML4_INDEX ((MINOS_HIGHER_HALF >> 39) & 0x1FFULL)
#define MINOS_VMM_BOOTSTRAP_PAGE_SIZE (2ULL * 1024 * 1024)
#define MINOS_VMM_BOOTSTRAP_MAX_PAGES \
    (MINOS_VMM_BOOTSTRAP_MAP_LIMIT / MINOS_VMM_BOOTSTRAP_PAGE_SIZE)
void vmm_init(const MinOS_BootInfo *info);
#endif
